# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
LABRADOR2_DATABASE_PASSWORD: "Constel1"
SECRET_KEY_BASE: "cc6b39b7306a8bac8628654937325d3da5f50b18d633372bd52f81ee0fdb61512472a0a66922087b6dda681909a115dfa91f35d3a294dc117e51c52acdbbb9c9"
